repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^mkdocs\.yml$  # Exclude mkdocs.yml due to PyYAML tags
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 25.1.0  # Updated to the latest version
    hooks:
    -   id: black
        additional_dependencies: ['.[jupyter]']
        stages: [commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML, types-Deprecated] # Added types-Deprecated
